### ISSUE TITLE
support different strategies for local store

### ISSUE THREAD

**Issue by pgte** [peer-base/peer-base#117]
Support providing different strategies for the local store implementation.

Local store provides storage for deltas, state (and, generally, other things in the future like membership).

The implementation should be replaceable by, for instance, a memory-only store, or a store that only saves the state into local store (and keeps deltas in memory).

- [ ] define interface
- [ ] implement "persistent" local store
- [ ] implement "memory-only" local store
- [ ] implement "state is persistent and deltas are memory-only" local store

**Comment by parkan** [comment]
deprecated in favor of MFS?

**Comment by pgte** [comment]
@parkan correct, closing.
