### ISSUE TITLE
Better discovery and dialing heuristic

### ISSUE THREAD

**Issue by dirkmc** [peer-base/peer-base#153]
There are some issues with discovery:
- It takes a long time for gossip to start up (around 15 seconds). This is because
  - Rendezvous does not send us peers who are already connected to the rendezvous server (fixed in https://github.com/libp2p/js-libp2p-websocket-star-rendezvous/pull/27, deploy in https://github.com/ipfs/infrastructure/issues/458)
  - To connect the peer to floodsub, we need to dial the peer and then floodsub will receive a `peer:connect` event and make a connection. Currently we wait a random amount of time (up to 5s) before dialing a peer so as not to overload new peers.
    In practice the peer may already have been dialed by the websocket star transport.
    _1. I propose a dialing heuristic that takes into account the number of peers known to the app._
  - When we dial a peer, we poll floodsub to see if it's interested in our app topic because floodsub did not inform us with an event (fixed in https://github.com/libp2p/js-libp2p-floodsub/issues/60)
    _2. We should listen for this event instead of polling_
- We repeatedly dial the same peers
  This is because rendezvous repeatedly emits `peer:connect` (every 10s by default)
  _3. I propose adding a wrapper around discovery that remembers which peers have been dialed_
    I suggest the wrapper's memory should have a time limit, and a limit on the number of peers
- Occasionally we do not dial on `peer` events, I think because of a bug in the dialing mechanism
  _4. Implementing the wrapper should take care of this_

I'm happy to work on a PR to fix these issues

**Comment by dirkmc** [comment]
@pgte one thing I'm not sure about, what is the purpose of [this block](https://github.com/ipfs-shipyard/peer-star-app/blob/master/src/transport/discovery.js#L132)?

**Comment by victorb** [comment]
> deploy in ipfs/infrastructure#458)

Been deployed now

**Comment by dirkmc** [comment]
@victorb wow you guys don't mess around :) Thanks!

**Comment by pgte** [comment]
@dirkmc this is great, thank you!
Trying to answer your question:
When trying to find if a peer is interested in the app, we need to make sure that he's in the inbound or outbound connection list, so that the connection accounting is correct.

(Thinking about this again, I'm not sure of why the peer would be in the inbound list if it wasn't in the peer ring, but I may be missing something...)

**Comment by pgte** [comment]
@dirkmc this was fixed by #200, right?

**Comment by dirkmc** [comment]
@pgte Yes, it was fixed - closing
