### ISSUE TITLE
RFC: rename to peer-base?

### ISSUE THREAD

**Issue by pgte** [peer-base/peer-base#164]
Thanks for idea @daviddias!

**Comment by jimpick** [comment]
I like it!

**Comment by daviddias** [comment]
Yes please! :D

**Comment by jimpick** [comment]
Doesn't seem to have a lot of other usage... I did find a (defunct?) Twitter account...

https://twitter.com/peerbase

I looked at archive.org for peerbase.org, but it doesn't appear to have ever had any real content (that was archived)

**Comment by jimpick** [comment]
Plus we can can use all sorts of "moon base" or "mars base" artwork to tie into the interplanetary theme. :-)

**Comment by victorb** [comment]
`peer-base` to replace `peer-star-app` or `peer-base` to replace `peer-star` as a whole?

**Comment by daviddias** [comment]
peer-base to replace peer-star-app

**Comment by daviddias** [comment]
@pgte seems you have enough 👍 and ❤️ to move forward with the proposal :)

**Comment by pgte** [comment]
Awesome! Moving on with this [here](https://github.com/peer-base/peer-base/issues/203).
