### ISSUE TITLE
Speed up collaboration membership establishment

### ISSUE THREAD

**Issue by dirkmc** [peer-base/peer-base#220]
Currently, peers periodically broadcast a hash of the peer ids of the members of a collaboration. If a peer receives a different hash, it switches to urgently broadcasting the CRDT of members until all peers agree on membership.

In order to minimize the time it takes for new peers to join a collaboration membership, I propose that
- instead of beginning broadcasts on startup, a peer should wait until it is connected to at least one other peer
- the first message it sends should contain the full CRDT (instead of a hash)
- if the number of members is low a peer should respond to a hash mismatch immediately, rather than waiting for the next tick (up to 1 second later)

**Comment by pgte** [comment]
These sound great to me!
