### ISSUE TITLE
regression: subcollaboration data getting mixed with main collaboration

### ISSUE THREAD

**Issue by jimpick** [peer-base/peer-base#232]
I tried out peer-base master e6c904f with peer-pad, and this happened:

<img width="1319" alt="screenshot 2019-01-14 12 13 05" src="https://user-images.githubusercontent.com/20886/51139102-ccb0a380-17f7-11e9-8d13-d98b27ac8d94.png">

I tried peer-base 0.12.0-rc3 and it also happened.

Reverting back to 0.11.1, it didn't happen.

**Comment by dirkmc** [comment]
Jim there's a fix that may help in my PR, do you want to try testing it out? https://github.com/peer-base/peer-base/pull/230

**Comment by jimpick** [comment]
> Jim there's a fix that may help in my PR, do you want to try testing it out? #230

Oops, just saw your comment. I'll try it out. I did a quick fix in #233, but yours might be better.

**Comment by jimpick** [comment]
@dirkmc I tried out #230, but it still has the issue.

**Comment by dirkmc** [comment]
Ok thanks, I guess we need to do some more digging
