### ISSUE TITLE
Collaboration gossip may not propagate to all members of collaboration

### ISSUE THREAD

**Issue by dirkmc** [peer-base/peer-base#242]
We use floodsub to [publish collaboration gossip messages](https://github.com/peer-base/peer-base/blob/master/src/collaboration/gossip.js#L49) with a topic [derived from the collaboration name](https://github.com/peer-base/peer-base/blob/master/src/collaboration/index.js#L198). However peers running floodsub [do not forward on messages unless the recipient peer has registered interest](https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/index.js#L123) in that particular topic. So if there is a linear connection `Peer A - Peer B - Peer C` and Peer A and Peer C are in collaboration `mycollab`, but Peer B is not, then messages broadcast by Peer A will not reach Peer C (and vice versa)

Note that is not a problem for App level gossip (used to establish membership) because all peers in the App register interest in the App topic, and connections are only made to other App peers.

**Comment by pgte** [comment]
@dirkmc Since a collaboration tends to form a connected network, is this a problem for collaboration-level gossip?

**Comment by dirkmc** [comment]
Ah yes, you're right, the collaboration members dial each other directly, so they will trigger floodsub to set up connections 👍
