### ISSUE TITLE
Random collaboration test not finishing

### ISSUE THREAD

**Issue by jimpick** [peer-base/peer-base#246]
With the new RGA implementation in delta-crdts (peer-base master), often the collaboration-random test will stall and not finish ... it's random, but I can sometimes get it to happen with 3 peers and 30 characters each.

Here's a capture with some extra debugging added (with [ANSI colours](https://github.com/theZiz/aha)!):

https://gateway.ipfs.io/ipfs/QmdHhLPw3R8mdr1bdCd3as2hSKjwYgxQZAbdExqvTTnxZ9

In this case, there are 3 peers, and 30 characters each, for a total of 90 characters.

You can see that both the "ums" and "umQ" peers manage to reach 90 characters. However, the "S8c" peer tops out at 58 characters.

All three peers reach a full vector clock: [ums:30 S8c:30 umQ:30]

Looking at the last thing S8c applies, I have logged this:

```
Jim S8c <- ums pull saving delta
  "45678"
State: S8c 58 [ums:30 S8c:30 umQ:30]
  Before: "abcdefg90abcdehifghiEFGHIJKLMNjOkjklPlmQmnopqrstuvwxyzABCD"
  After: "abcdefg90abcdehifghiEFGHIJKLMNjOkjklPlmQmnopqrstuvwxyzABCD"
```

The delta being applied has characters for "45678", but those aren't showing up in the final .value() after they are applied.

I think that points to a problem with the new RGA CRDT algorithm.

I'll try to capture some trace data so I can make a test case for js-delta-crdts.

My branch with all the extra ad-hoc diagnostic logging is here: https://github.com/jimpick/peer-base/tree/jim-trace-protocol

**Comment by pgte** [comment]
@jimpick thank you, a test case is greatly appreciated!
I'll also be trying to break the RGA implementation meanwhile..

**Comment by jimpick** [comment]
I'm digging through some traces ... I think the CRDT is fine - the issue is that some of the dependencies didn't get synced - so, in the above example, "45678" follows some other characters that didn't get synced ... it probably was properly applied to the CRDT, but it's being stored as "unconnected" edges.

I've got the scenario captured in a trace ... once I get it isolated, I'll write up a detailed issue.

**Comment by jimpick** [comment]
I think I figured it out. I can try to write it up in detail tomorrow... with the trace I used.

It appears that when we are collecting deltas for the batch, we're using the optional third argument for vectorclock.isDeltaInteresting() to filter out delta for the peer we are sending too.

https://github.com/peer-base/peer-base/blob/eeeec24c659010b7bdbb872cb5dee2c175cae833/src/collaboration/shared.js#L168

The problem is that we are also saving the batch as a delta, and in certain circumstances involving lazy replication, we might send the batch to a third-party peer that might not have the deltas that were filtered out.

When the third-party peer gets the batch, the vector clock for the batch claims to have covered the deltas that were filtered out ... so the third-party peer advances its copy of the clock, and so never tries to fetch the missing delta.

**Comment by pgte** [comment]
@jimpick great catch!
Could you try removing the 3rd argument for `isDeltaInteresting` and see if you can still break it?

**Comment by jimpick** [comment]
I removed it, but it still generates batches missing deltas. eg.

```
Line: 1700 Jim umQ -> ums push batches [ums:19 S8c:18 umQ:29] -> [ums:21 S8c:18 umQ:27] (Push batches)
Line: 1701 Jim deltaBatches since:  [ums:21 S8c:18 umQ:27] target: QmdXPocZdyJyzXTCc5Z8Mfw35KV1ezC1St8es8UDYKMums
Line: 1702   Delta: [ums:18 S8c:18 umQ:27] [umQ:1] "6"
Line: 1703   Delta: [ums:19 S8c:18 umQ:28] [umQ:1] "7"
Line: 1704   Batch: [ums:18 S8c:18 umQ:27] [ums:1 umQ:2] "67"
```

It's missing this earlier delta:

```
[ums:18 S8c:18 umQ:26] [ums:1] "á"
```

Probably because it was pushing to ums, which already had the delta...

I think I know what to look for now. I just have to look for batches that advance the clock more notches than are included in the delta.

I'm going to add some more console.log() statements so I can understand how it's generating the batches.

**Comment by jimpick** [comment]
I finally figured it out... as the batch is constructed, the "previous" clock is calculated from a minimum of the vector clocks, which means it will often go back in time to before the 'since' time. So we need to check for that, and include any extra deltas that are dependencies of the ones we are adding to the batch.

It's time for bed here, but this commit on my experimental branch fixes the problem:

https://github.com/jimpick/peer-base/commit/e00ecdbc156ca8e6ae5c9acd5545e81ba2669f0e

It's a little ugly to throw an exception like I do there, but that seemed like the easiest thing to do for now.

I also had to fix some issues with how the vectorclock.minimum() function dealt with undefined peers in the vector clock ... it no longer sets the vector clock to zero if the peer is missing. I also made sure the vector clocks get a zero clock when they are initialized.

Tomorrow, I can clean up the patch (add tests somehow?) and do a proper PR.

**Comment by pgte** [comment]
@jimpick good call! I guess not all deltas are mergeable, some information may be lost when assuming so.
There's already some logic to determine if a delta is mergeable or not, so I guess we should extend it to determine if a new delta extends the current batch. Please tell me if you'd like some help with that.

**Comment by jimpick** [comment]
I collected some data in #257 ... all the test failures I'm seeing now are due to Node.js lockups, or just  really slow convergence (hitting the test timeout). I'll close this issue, and we can discuss ways to make it better in other issues.
