### ISSUE TITLE
Make @jimpick new maintainer

### ISSUE THREAD

**Issue by parkan** [peer-base/peer-base#269]
Let's make @jimpick new maintainer on peer-base (here and on npm) so we can push up new versions

@pgte

**Comment by pgte** [comment]
@jimpick what's your npm handle?

**Comment by jimpick** [comment]
https://www.npmjs.com/~jimpick

:-)

**Comment by pgte** [comment]
Done.

<img width="407" alt="1__bash" src="https://user-images.githubusercontent.com/47910/54809472-468f5e00-4c7b-11e9-8300-9f50c2e9144e.png">

**Comment by pgte** [comment]
@jimpick do you want to do a PR to set you as a maintainer on the manifest?

**Comment by jimpick** [comment]
I did it as PR #270 ... there wasn't anybody named as a maintainer currently.
