### ISSUE TITLE
ERROR: Can't resolve 'peer-star-app'

### ISSUE THREAD

**Issue by realChainLife** [peer-base/peer-base#304]
Can't run the app server - fails to compile with error:

    Failed to compile.
    ./node_modules/peer-star-react/src/withCollaboration.js
    Module not found: Can't resolve 'peer-star-app' in '/home/peer-base/examples/react- 
    app/node_modules/peer-star-react/src'

Steps to recreate, followed the step in the readme.md

**Comment by jimpick** [comment]
Thanks for reporting this.

I'm hoping to replace that example with a much simpler one. I haven't had much time available to work on peer-base recently.

'peer-star-app' was the original name for 'peer-base', so if you want to try to fix it, it probably needs to be renamed there.

**Comment by realChainLife** [comment]
Thanks Jim, I'll make those changes and try again.
