### ISSUE TITLE
Shall I move the remaining peer-* repos to peer-base Org?

### ISSUE THREAD

**Issue by daviddias** [peer-base/peer-base#316]
Repos being:
- https://github.com/ipfs-shipyard/peer-pad
- https://github.com/ipfs-shipyard/peer-crdt
- https://github.com/ipfs-shipyard/peer-pad-core
- https://github.com/ipfs-shipyard/peer-crdt-ipfs
- https://github.com/ipfs-shipyard/peer-base-pinner
- https://github.com/ipfs-shipyard/peer-blog
- https://github.com/ipfs-shipyard/peer-identity
- https://github.com/ipfs-shipyard/peer-crdt-bind-codemirror
- https://github.com/ipfs-shipyard/peer-crdt-example
- https://github.com/ipfs-shipyard/peer-star-network-vis
- https://github.com/ipfs-shipyard/peer-star-react
- https://github.com/ipfs-shipyard/peer-star-infra
- https://github.com/ipfs-shipyard/peer-cacl
- https://github.com/ipfs-shipyard/peerpad-peer-crdt
- https://github.com/ipfs-shipyard/peer-star-peer-color
- https://github.com/ipfs-shipyard/peer-identity-demo
- https://github.com/ipfs-shipyard/peer-crdt-platform
- https://github.com/ipfs-shipyard/peer-crdt-textarea-binding
- https://github.com/ipfs-shipyard/peer-star-network-vis-react

**Comment by jimpick** [comment]
I think most of them are really old and aren't used by the present code.

I think it would be nice to move the following ones:

* https://github.com/ipfs-shipyard/peer-pad
* https://github.com/ipfs-shipyard/peer-base-pinner
* https://github.com/ipfs-shipyard/peer-star-network-vis
* https://github.com/ipfs-shipyard/peer-star-network-vis-react

All the other ones are really old and it might be best to archive them somehow.

It might be good to move the following closely related libraries as well:

* https://github.com/ipfs-shipyard/js-delta-crdts
* https://github.com/ipfs-shipyard/js-delta-crdts-msgpack-codec
